package edu.poly.common;

public enum PageType {
	USER_MANAGEMENT_PAGE, REPORT_MANAGERMENT_PAGE, VIDEO_MANAGERMENT_PAGE //trang quản trị ng dùng, QLY THỐNG KÊ, QLY VIDEO
	
	,SITE_HOME_PAGE, SITE_LOGIN_PAGE, SITE_REGISTRATION_PAGE,
	SITE_CHANGE_PASSWORD_PAGE, SITE_EDIT_PROFILE_PAGE, SITE_FORGOT_PASSWORD_PAGE, SITE_VIDEO_DETAL_PAGE,
	SITE_FAVORITE_PAGE, SITE_SHARE_PAGE, SITE_ABOUT_PAGE, SITE_CONTACT_PAGE
}
